### ISSUE TITLE
Gitea fails to process test task in laconic-sdk

### ISSUE THREAD

**Issue by dboreham** [cerc-io/hosting#26]
Migrated the [laconic-sdk](https://github.com/cerc-io/laconic-sdk/actions/workflows/test.yml) repo and made a PR to test Actions.
Nothing runs. In Gitea log I see:

```
2023/03/28 14:17:05 ...actions/workflows.go:71:DetectWorkflows() [W] ignore invalid workflow "test.yml": unknown on type: <nil>
```

The action runs on GitHub:

![image](https://user-images.githubusercontent.com/1649760/228268795-1b2c3ca3-0731-4df6-bbcd-fa0de7290a1a.png)

**Comment by telackey** [comment]
There appear to be a be a bug in nektos/act (or at least gitea's fork of it) which does not process the YAML of an `on` specification correctly when there are no child nodes, eg:

```
on:
  pull_request:
  push:
    branches:
      - main
      - release/**
```

Specifically, the error was here, because `v` is nil in this instance: https://gitea.com/gitea/act/src/commit/929ea6df751b98f399498d35bb1c68f4e6c15e14/pkg/jobparser/model.go#L166

But it looks like it was fixed a few days ago: https://gitea.com/gitea/act/commit/3daf3132057d33bee325857b016a60db332fd050

In my local testing, I was able to make it happy by adding a `types` child, but interestingly when running in gitea (and I tried both 1.19 and the latest 1.20.0 dev build, which I hoped would have the latest act, but it doesn't seem like it is quite up to date yet) the only thing to satisfy it was to add a `branches` child.

In the meantime, a fairly simple workaround is to change it to:

```
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - release/**
```
