### ISSUE TITLE
Support building go containers

### ISSUE THREAD

**Issue by dboreham** [cerc-io/hosting#49]
When running a go build inside a container build, that depends on private modules pulled from the host gitea, provide an access token such that said modules can be pulled and the build succeed.

**Comment by dboreham** [comment]
Reproduction: https://git.vdb.to/cerc-io/plugeth-statediff/actions/runs/11/jobs/1

**Comment by dboreham** [comment]
The golang part of this seems to be a well known problem, e.g. : https://jwenz723.medium.com/fetching-private-go-modules-during-docker-build-5b76aa690280

**Comment by telackey** [comment]
Roy already made some changes, but I added this on top: https://git.vdb.to/cerc-io/plugeth-statediff/pulls/4

It works for me, would be flexible for using multiple tokens if required, and the multistage build prevents the secrets from leaking into the final image.

**Comment by dboreham** [comment]
Reopening since we haven't proven the solution to work yet, and also we should add some doc in this repo about how to use it.

**Comment by telackey** [comment]
I created an access token for the `cerccicd` user account and exposed it as a secret for the organization called `CICD_REPO_TOKEN`.

Inside a workflow file you would reference it as: `${{ secrets.CICD_REPO_TOKEN }}`, for example:

```
      - name: "Build docker image"
        env:
          GIT_VDBTO_TOKEN: ${{ secrets.CICD_REPO_TOKEN }}
        run: |
          docker build . -t cerc/myproj --build-arg GIT_VDBTO_TOKEN="$GIT_VDBTO_TOKEN"
```

Here is a PR for plugeth-statediff using it:
https://git.vdb.to/cerc-io/plugeth-statediff/pulls/5

And here is plugeth:
https://git.vdb.to/cerc-io/plugeth/pulls/2
